name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        run:
          composer update

      - name: PHPUnit
        run: vendor/bin/phpunit --verbose
